import streamlit as st
import pandas as pd

# Set the page layout to be wide for better table viewing.
st.set_page_config(layout="wide")

st.title("Contracts Data Viewer 📊")
st.write("Upload the CSV file generated by the scraper to view the data.")

# Create a file uploader widget in the web app.
uploaded_file = st.file_uploader("Choose your contracts_data.csv file", type="csv")

# This block runs only after a file has been uploaded.
if uploaded_file is not None:
    try:
        # Read the uploaded CSV file into a Pandas DataFrame.
        df = pd.read_csv(uploaded_file)
        
        st.header("Interactive Contracts Table")
        st.info(f"Displaying {len(df)} contracts.")
        
        # Display the DataFrame as an interactive table.
        # Streamlit automatically adds sorting and searching.
        st.dataframe(df)

    except Exception as e:
        # Show an error message if the file can't be read.
        st.error(f"An error occurred: {e}")

